#spring:
#  security:
#    user:
#      name: user
#      password: default

logging:
  level:
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.config: DEBUG
    org.springframework.security: DEBUG
